name: Polarisvbc
favicon: null
layout_spectrum: 0.48412
typography_spectrum: 0.4862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111820'
    - '#1ca2aa'
    - '#f36f26'
    - '#969275'
    - '#375b5c'
  brandStrength: 0.6875
  lightness: 0.6155176269821823
  saturation: 0.7821715553291142
  rhythmicContrast: 0.75
purpose: []
